### ISSUE TITLE
Allow restricting environmentss the initializers run in

### ISSUE THREAD

**Issue by igorshapiro** [WisePricer/quadro#125]
Here's a possible solution. In `test/quadro.yml`:

```yaml
initializers:
  # Shorthand
  jobs: false
  # Or
  jobs:
    run: false
```

@tomeresk WDYT?
