### ISSUE TITLE
External API: enable to use defaults for retry

### ISSUE THREAD

**Issue by rudovjan** [WisePricer/quadro#226]
```yml
productCatalog:
  host: localhost
  timeout: 1000
  retry:
```

will not define retry with default values

```yml
productCatalog:
  host: localhost
  timeout: 1000
  retry:
     times: 5
```

You have to at least specify one of retry attributes to get rest as defaults
